_wandb:
    value:
        cli_version: 0.22.2
        e:
            u5ygc3utzae83oifcm2gs9m6dtikh453:
                codePath: exam_wandb\wandb_init.ipynb
                codePathLocal: exam_wandb\wandb_init.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999286632448"
                        used: "170976608256"
                email: rlaqudwn123456@gmail.com
                executable: c:\Users\rlaqu\miniconda3\envs\upstage312_gpu\python.exe
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-5ca33cc0-1f1b-3ed3-0df8-d7bb9a7ad4dc
                host: 김병주
                memory:
                    total: "17102516224"
                os: Windows-11-10.0.26100-SP0
                program: c:\develop\exam_wandb\wandb_init.ipynb
                python: CPython 3.12.12
                root: c:\develop
                startedAt: "2025-10-26T10:07:08.033436Z"
                writerId: u5ygc3utzae83oifcm2gs9m6dtikh453
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
